import "./globals.css";
import { Inter } from "next/font/google";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Capital Rush</title>
        {/* Below is the Google tag for this account. Copy and paste it in the code of every page of your website, immediately after the <head> element. Don’t add more than one Google tag to each page. */}
        {/* <!-- Google tag (gtag.js) --> */}
        <script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-1XBWNXWCV6"
        ></script>
        {/* <script>
          {" "}
          window.dataLayer = window.dataLayer || []; function gtag()
          {dataLayer.push(arguments)} gtag('js', new Date()); gtag('config',
          'G-1XBWNXWCV6');
        </script> */}
      </head>
      <body className={inter.className}>
        {children}
        <script src="../path/to/flowbite/dist/flowbite.min.js"></script>
      </body>
    </html>
  );
}
